// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/google/wire"
	"github.com/tilau2328/x/src/go/service/repo/go/package/provider"
	"github.com/tilau2328/x/src/go/service/repo/go/package/services"
)

// Injectors from wire.go:

func Init() (provider.GolangProvider, func(), error) {
	serviceService := services.NewService()
	return serviceService, func() {
	}, nil
}

// wire.go:

var Set = wire.NewSet(services.NewService, wire.Bind(new(provider.GolangProvider), new(*services.Service)))
