package model

func (n *ArrayType) Decorations() *NodeDecs      { return &n.Decs.NodeDecs }
func (n *AssignStmt) Decorations() *NodeDecs     { return &n.Decs.NodeDecs }
func (n *BadDecl) Decorations() *NodeDecs        { return &n.Decs.NodeDecs }
func (n *BadExpr) Decorations() *NodeDecs        { return &n.Decs.NodeDecs }
func (n *BadStmt) Decorations() *NodeDecs        { return &n.Decs.NodeDecs }
func (n *BasicLit) Decorations() *NodeDecs       { return &n.Decs.NodeDecs }
func (n *BinaryExpr) Decorations() *NodeDecs     { return &n.Decs.NodeDecs }
func (n *BlockStmt) Decorations() *NodeDecs      { return &n.Decs.NodeDecs }
func (n *BranchStmt) Decorations() *NodeDecs     { return &n.Decs.NodeDecs }
func (n *CallExpr) Decorations() *NodeDecs       { return &n.Decs.NodeDecs }
func (n *CaseClause) Decorations() *NodeDecs     { return &n.Decs.NodeDecs }
func (n *ChanType) Decorations() *NodeDecs       { return &n.Decs.NodeDecs }
func (n *CommClause) Decorations() *NodeDecs     { return &n.Decs.NodeDecs }
func (n *CompositeLit) Decorations() *NodeDecs   { return &n.Decs.NodeDecs }
func (n *DeclStmt) Decorations() *NodeDecs       { return &n.Decs.NodeDecs }
func (n *DeferStmt) Decorations() *NodeDecs      { return &n.Decs.NodeDecs }
func (n *Ellipsis) Decorations() *NodeDecs       { return &n.Decs.NodeDecs }
func (n *EmptyStmt) Decorations() *NodeDecs      { return &n.Decs.NodeDecs }
func (n *ExprStmt) Decorations() *NodeDecs       { return &n.Decs.NodeDecs }
func (n *Field) Decorations() *NodeDecs          { return &n.Decs.NodeDecs }
func (l *FieldList) Decorations() *NodeDecs      { return &l.Decs.NodeDecs }
func (n *File) Decorations() *NodeDecs           { return &n.Decs.NodeDecs }
func (n *ForStmt) Decorations() *NodeDecs        { return &n.Decs.NodeDecs }
func (n *FuncDecl) Decorations() *NodeDecs       { return &n.Decs.NodeDecs }
func (n *FuncLit) Decorations() *NodeDecs        { return &n.Decs.NodeDecs }
func (n *FuncType) Decorations() *NodeDecs       { return &n.Decs.NodeDecs }
func (n *GenDecl) Decorations() *NodeDecs        { return &n.Decs.NodeDecs }
func (n *GoStmt) Decorations() *NodeDecs         { return &n.Decs.NodeDecs }
func (n *Ident) Decorations() *NodeDecs          { return &n.Decs.NodeDecs }
func (n *IfStmt) Decorations() *NodeDecs         { return &n.Decs.NodeDecs }
func (n *ImportSpec) Decorations() *NodeDecs     { return &n.Decs.NodeDecs }
func (n *IncDecStmt) Decorations() *NodeDecs     { return &n.Decs.NodeDecs }
func (n *IndexExpr) Decorations() *NodeDecs      { return &n.Decs.NodeDecs }
func (n *IndexListExpr) Decorations() *NodeDecs  { return &n.Decs.NodeDecs }
func (n *InterfaceType) Decorations() *NodeDecs  { return &n.Decs.NodeDecs }
func (n *KeyValueExpr) Decorations() *NodeDecs   { return &n.Decs.NodeDecs }
func (n *LabeledStmt) Decorations() *NodeDecs    { return &n.Decs.NodeDecs }
func (n *MapType) Decorations() *NodeDecs        { return &n.Decs.NodeDecs }
func (n *Package) Decorations() *NodeDecs        { return nil }
func (n *ParenExpr) Decorations() *NodeDecs      { return &n.Decs.NodeDecs }
func (n *RangeStmt) Decorations() *NodeDecs      { return &n.Decs.NodeDecs }
func (n *ReturnStmt) Decorations() *NodeDecs     { return &n.Decs.NodeDecs }
func (n *SelectStmt) Decorations() *NodeDecs     { return &n.Decs.NodeDecs }
func (n *SelectorExpr) Decorations() *NodeDecs   { return &n.Decs.NodeDecs }
func (n *SendStmt) Decorations() *NodeDecs       { return &n.Decs.NodeDecs }
func (n *SliceExpr) Decorations() *NodeDecs      { return &n.Decs.NodeDecs }
func (n *StarExpr) Decorations() *NodeDecs       { return &n.Decs.NodeDecs }
func (n *StructType) Decorations() *NodeDecs     { return &n.Decs.NodeDecs }
func (n *SwitchStmt) Decorations() *NodeDecs     { return &n.Decs.NodeDecs }
func (n *TypeAssertExpr) Decorations() *NodeDecs { return &n.Decs.NodeDecs }
func (n *TypeSpec) Decorations() *NodeDecs       { return &n.Decs.NodeDecs }
func (n *TypeSwitchStmt) Decorations() *NodeDecs { return &n.Decs.NodeDecs }
func (n *UnaryExpr) Decorations() *NodeDecs      { return &n.Decs.NodeDecs }
func (n *ValueSpec) Decorations() *NodeDecs      { return &n.Decs.NodeDecs }
